import { DM_Sans } from "next/font/google";
import styles from "@/styles/globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const dmSans = DM_Sans({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--ff-primary",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" style={{ styles }} className={dmSans.className}>
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
